skz = ['Hyunjin','Lee Know', 'Bang Chan', 'Changbin', 'Felix', 'Seungmin', 'Han', 'IN']
print(skz)
count = skz.count('Hyunjin')
print(count)
count= skz.count('Seungmin')
print(count)
index = skz.index('Seungmin')
print(index)
index = skz.index('Hyunjin', 0)
print(index)
skz.reverse()
print(skz)
skz.append('Stay')
print(skz)
skz.sort()
print(skz)

retirar_item = skz.pop(5)
print(skz.pop)
print(retirar_item)

TeenTitans = ['Robin', 'Raven','Starfire', 'Beast Boy']
skz.extend(TeenTitans)
print(skz)
skz.insert(4,'Terra')
print(skz)
skz.remove('Terra')
print(skz)
skz.clear()
print(skz)
skz.copy()
print(skz)